spring:
    mvc:
        view:
            prefix: /
            suffix: .html
    datasource:
        url: jdbc:h2:mem:appdb;
        driverClassName: org.h2.Driver
        username: sa
        password:
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
server:
    port: 9000